### ISSUE TITLE
please make a review system

### ISSUE THREAD

**Issue by BMaxV** [flathub-infra/website#3571] opened 2024-07-12 15:54 UTC
Hi,

please make a review system.

I have a seen https://github.com/flathub-infra/website/issues/50 and https://github.com/flathub-infra/linux-store-frontend/pull/311

I apologize if you think this is a duplicate. I'm not really deep into web things, so I can't judge how far those issues / PRs have progressed and which solution you will ultimately choose.

But I am a user, I got a pack from flathub and I had some problems. Nothing critical and nothing anyone but the distribution people can do anything about. Specifically about theming. Anyway: There is no review system. There are no comments. On flathub. I can't leave a star review, I can't leave a comment. That's kinda bad.

My issue wasn't critical, **but other people's issues might be**. 

There is no way to warn anyone about "minor issues". I"m sure you have a report system for "this is actually really seriously malware that's going to steal your data etc.". At least I hope that you do. (If it exists, I couldn't find it quickly. You can hide it too, maybe in developer settings or in the profile or a "security" thing two layers down where people don't immediately spam report things, but you probably want one?)

Anyway, I'm a user and "this is a real issue now". Idk.

Thank you for your work!

**Comment by bbhtt** [comment] 2024-07-12 16:50
Duplicate of https://github.com/flathub-infra/website/issues/50

**Comment by razzeee** [comment] 2024-07-12 22:17
You should report issues to the packagers, see the link section. That should be what a review section is used for.

**Closed** 2024-07-12 22:17 UTC
