### ISSUE TITLE
Icons are visibly compressed

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#3684] opened 2024-08-07 10:59 UTC
Whatever lossy compression we're doing on icons is a bit too lossy, there are visible artifacts on many icons:

![image](https://github.com/user-attachments/assets/6f2d5b3e-745b-4e4a-a386-e7e338a7430d)

**Comment by razzeee** [comment] 2024-08-07 11:23
Duplicate of https://github.com/flathub-infra/website/issues/3652

**Closed by razzeee** 2024-08-07 11:23 UTC
